2011-team-phantom/phantom

- .gitignore
- client/app.js
- client/components/LinkPlaid.js
- client/index.js
- package-lock.json
- package.json
- public/index.html
- server/index.js
User can log in with bank account and render prices of past purchases
> Plaid start

- package-lock.json
- package.json
- server/db/db.js
- server/db/index.js
- server/db/models/index.js
- server/db/models/users.js
- server/index.js
> added mongodb

- client/Routes.js
- client/components/Login.js
- client/index.js
- server/auth/index.js
- server/db/models/users.js
- server/index.js
Added FE login component and connected BE route
> user login

- client/components/LinkPlaid.js
- client/components/Login.js
- client/index.js
- server/auth/index.js
- server/db/db.js
- server/index.js
Session store in mongodb persists across refresh.
Cleaned up console logs and comments
> Session setup

- client/Routes.js
- client/app.js
- client/components/LinkPlaid.js
- client/components/Login.js
- client/history.js
- client/index.js
- client/store/user.js
- package-lock.json
- package.json
> bug: fixing history bug by downgrading to v4.10.1

- client/Routes.js
- client/components/LinkPlaid.js
- client/components/Login.js
- client/components/Signup.js
- client/store/user.js
- server/auth/index.js
- server/db/models/users.js
> signup component and route

- client/components/Budget.js
- client/components/LinkPlaid.js
- client/store/index.js
- client/store/transactions.js
- server/index.js
> Created transfer store

- client/Routes.js
- client/components/Budget.js
- client/components/LinkPlaid.js
> FEATURE: User's spending categories page

- client/Routes.js
- client/components/AddBudget.js
- client/components/Budget.js
- client/components/Navbar.js
- client/components/Signup.js
- client/store/transactions.js
- server/api/index.js
- server/db/models/users.js
> added  budget prop to database

- client/components/LinkPlaid.js
- client/components/Login.js
- client/store/transactions.js
- client/store/user.js
- server/auth/index.js
- server/index.js
Checks if access token exists before pulling transactions
> Feature: transactions pulled with access token from user, added to redux

- client/components/Budget.js
- client/store/transactions.js
- server/api/index.js
> FEATURE: User can update their budget goals

- client/Routes.js
- client/app.js
- client/components/LinkPlaid.js
- client/components/Navbar.js
- client/components/Transactions.js
- package-lock.json
- package.json
- public/index.html
- public/style.css
Creating navbar that persist with every page. 
Creating transactions page and loading transactions in transactions page.
> Feat: creating navbar and transactions page

- client/Routes.js
- client/components/Login.js
- client/components/Navbar.js
- client/components/Transactions.js
- client/store/user.js
- server/index.js
Logged in user gets directed to the transaction page.
Home page is the login page.
> chore: rearranging routes for a logged in user

- client/components/LinkPlaid.js
- client/components/Login.js
- client/components/Transactions.js
- client/store/transactions.js
- client/store/user.js
- server/auth/index.js
- server/index.js
gets user access token before pulling transactions from plaid
redirects to transactions after user links bank 
clean up console logs
> Chore: fixed new user login access token, redirects to transactions, clean up logs

- deploy
- package.json
> feat: deploy script

- deploy
- package-lock.json
- package.json
- public/bundle.js.LICENSE.txt
- server/index.js
- webpack.config.js
> Feat: User gets transactions from the past six months

- client/components/Glance.js
- webpack.config.js
Total table on at-a-glance page
resized pie chart
> Category total

- client/components/AddBudget.js
- client/components/Glance.js
- client/components/LinkPlaid.js
- client/components/Login.js
- client/components/Navbar.js
- client/components/Signup.js
- client/components/Transactions.js
- public/bundle.js.LICENSE.txt
- public/style.css
- webpack.config.js
> STYLING: addbudget, login, signup

- client/components/Budget.js
- client/store/transactions.js
- public/style.css
- server/api/index.js
> STYLING: Budget page

- client/components/Navbar.js
> making the nav buttons reactive and adding the users email to the navbar

- client/components/Budget.js
- client/components/Glance.js
> added progress bar to glance page

- client/components/LinkPlaid.js
- client/components/Transactions.js
> changed timeout of linkplaid

- client/components/Transactions.js
transactions isn't called an infinite amount of times
> transactions doesnt get called so many times

- client/components/Budget.js
- public/style.css
> STYLING: Budget page uses financial decimal point and shows percentage progress bar

- client/components/Navbar.js
- public/style.css
> Navbar fix

- client/components/Glance.js
- public/style.css
center components on glance page
set max width
> center glance component and max width

- client/components/AddBudget.js
> BUG: User can input addBudget total

- client/components/Glance.js
- client/components/Navbar.js
- client/components/Transactions.js
- client/store/transactions.js
- client/store/user.js
- server/auth/index.js
> refactor: privacy, categories, tables

- client/components/Glance.js
- public/style.css
> glance re-renders when budget is updated, css on progress bars

- client/Routes.js
- client/components/Navbar.js
> refactoring navbar menu

- client/components/AddBudget.js
- client/components/Login.js
- client/components/Signup.js
- client/store/user.js
- package-lock.json
- package.json
- server/auth/index.js
> BUG: Form validations on login, signup, and addbudget

- client/Routes.js
- client/components/AddBudget.js
- client/components/Glance.js
- client/components/Navbar.js
- client/store/transactions.js
- server/index.js
> feat: logout button and remove console log

- client/components/Budget.js
- client/components/Transactions.js
- package-lock.json
- package.json
- server/index.js
> FEATURE: User can filter between 3, 6, 12 months view on transactions page

- client/components/Budget.js
> Refactored categoryOptions in budget

- client/components/AddBudget.js
- client/components/AddTransaction.js
- client/components/Budget.js
- client/components/EditUser.js
- client/components/Footer.js
- client/components/Glance.js
- client/components/LinkPlaid.js
- client/components/Login.js
- client/components/Navbar.js
- client/components/Signup.js
- client/components/Transactions.js
- client/history.js
- client/index.js
- client/store/transactions.js
- public/style.css
- server/api/index.js
- server/auth/index.js
- server/index.js
> Refactor: Removing logs and unnecessary code and refactoring

- client/components/Navbar.js
- public/style.css
> refactoring the navbar

- client/components/Login.js
- client/components/Signup.js
- client/store/user.js
> FIX: Error message on login and signup page

- client/components/Footer.js
- client/components/Glance.js
- client/components/Transactions.js
> Feature: added date filter to glance, footer links, colors

- client/components/Budget.js
> Refactor: Removed moment.js dependency

- client/components/AddBudget.js
> FEATURE: User cannot input a budget amount greater than their monthly income

- client/components/LinkPlaid.js
- manifest.json
- package-lock.json
- package.json
- public/index.html
- server/api/index.js
> renamed app to plutus

- client/components/AddBudget.js
- client/components/CoinAnimation.js
- client/components/EditUser.js
- client/components/PigAnimation.js
- client/store/index.js
- package.json
> cleaning up files, adding a description

- README.md
> Documentation: Updated Readme

- client/components/Budget.js
- client/components/EditUser.js
- package-lock.json
- public/style.css
> bugFix: fixed number update in form, refactor: budget filter

- client/components/Navbar.js
> chore: plaid link is only visible to new users that dont have plaid connected
